
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SoloCode JSHDVR
 */
public class APAP extends javax.swing.JFrame {

    /**
     * Creates new form APAP
     */
    public APAP() {
        initComponents();
        this.setLocationRelativeTo(null);
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bgPanel = new javax.swing.JPanel();
        dispayPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        profilePanel = new javax.swing.JPanel();
        lnField = new javax.swing.JTextField();
        fnField = new javax.swing.JTextField();
        yearBox = new javax.swing.JComboBox<>();
        courseBox = new javax.swing.JComboBox<>();
        emailField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        genderBox = new javax.swing.JComboBox<>();
        snField = new javax.swing.JTextField();
        imgLocation = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        enablerPanel = new javax.swing.JPanel();
        nameCheck = new javax.swing.JCheckBox();
        enalblerTxt = new javax.swing.JLabel();
        cyCheck = new javax.swing.JCheckBox();
        gCheck = new javax.swing.JCheckBox();
        cnCheck = new javax.swing.JCheckBox();
        eCheck = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        topBarPanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        addProfile = new javax.swing.JButton();
        save = new javax.swing.JButton();
        searchStudent = new javax.swing.JButton();
        editStudent = new javax.swing.JButton();
        openFile = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sort = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        timeIn = new javax.swing.JCheckBox();
        sortName = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        sortSno = new javax.swing.JCheckBox();
        logoPanel = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        logo8 = new javax.swing.JLabel();
        logo9 = new javax.swing.JLabel();
        logo10 = new javax.swing.JLabel();
        logo11 = new javax.swing.JLabel();
        logo12 = new javax.swing.JLabel();
        logo13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        printSno = new javax.swing.JLabel();
        printFname = new javax.swing.JLabel();
        printLname = new javax.swing.JLabel();
        printGender = new javax.swing.JLabel();
        printCourse = new javax.swing.JLabel();
        printYear = new javax.swing.JLabel();
        printCnumber = new javax.swing.JLabel();
        printEmail = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        printTime = new javax.swing.JLabel();
        printTime1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanel.setBackground(new java.awt.Color(156, 203, 193));
        bgPanel.setForeground(new java.awt.Color(0, 102, 102));
        bgPanel.setPreferredSize(new java.awt.Dimension(550, 450));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dispayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT NUMBER", "FULL NAME", "DTR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        dispayPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 410));

        bgPanel.add(dispayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 480, 410));

        profilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lnField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lnField.setText("LAST NAME");
        lnField.setEnabled(false);
        lnField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnFieldFocusLost(evt);
            }
        });
        lnField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnFieldMouseClicked(evt);
            }
        });
        lnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnFieldActionPerformed(evt);
            }
        });
        profilePanel.add(lnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 30));

        fnField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fnField.setText("FIRST NAME");
        fnField.setEnabled(false);
        fnField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnFieldFocusLost(evt);
            }
        });
        fnField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fnFieldMouseExited(evt);
            }
        });
        fnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnFieldActionPerformed(evt);
            }
        });
        profilePanel.add(fnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 30));

        yearBox.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        yearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"YEAR\"", "1", "2", "3", "4" }));
        yearBox.setEnabled(false);
        yearBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearBoxActionPerformed(evt);
            }
        });
        profilePanel.add(yearBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, 30));

        courseBox.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        courseBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"COURSE\"", "ACT", "BSIT", "BSCS", "BSEMC", "" }));
        courseBox.setEnabled(false);
        courseBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseBoxActionPerformed(evt);
            }
        });
        profilePanel.add(courseBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 30));

        emailField.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        emailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailField.setText("E-MAIL");
        emailField.setEnabled(false);
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailFieldMouseClicked(evt);
            }
        });
        profilePanel.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, 30));

        contactField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contactField.setText("CONTACT NO.");
        contactField.setEnabled(false);
        contactField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactFieldFocusLost(evt);
            }
        });
        contactField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactFieldMouseClicked(evt);
            }
        });
        contactField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactFieldKeyTyped(evt);
            }
        });
        profilePanel.add(contactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 180, 30));

        genderBox.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        genderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"GENDER\"", "MALE", "FEMALE" }));
        genderBox.setEnabled(false);
        profilePanel.add(genderBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 30));

        snField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        snField.setText("STUDENT NUMBER");
        snField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                snFieldFocusLost(evt);
            }
        });
        snField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                snFieldMouseClicked(evt);
            }
        });
        snField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snFieldActionPerformed(evt);
            }
        });
        snField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                snFieldKeyTyped(evt);
            }
        });
        profilePanel.add(snField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        imgLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        profilePanel.add(imgLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 180, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Attach image");
        jButton1.setAutoscrolls(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        profilePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 180, 30));

        enablerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameCheck.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        nameCheck.setText("NAME");
        nameCheck.setToolTipText("");
        nameCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCheckActionPerformed(evt);
            }
        });
        enablerPanel.add(nameCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 20));

        enalblerTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enalblerTxt.setText("ENABLER");
        enalblerTxt.setToolTipText("DATA ENABLER");
        enablerPanel.add(enalblerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        cyCheck.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cyCheck.setText("COURSE/YEAR");
        cyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyCheckActionPerformed(evt);
            }
        });
        enablerPanel.add(cyCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 20));

        gCheck.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        gCheck.setText("GENDER");
        gCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gCheckActionPerformed(evt);
            }
        });
        enablerPanel.add(gCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 90, 20));

        cnCheck.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cnCheck.setText("CONTACT");
        cnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnCheckActionPerformed(evt);
            }
        });
        enablerPanel.add(cnCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, 20));

        eCheck.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        eCheck.setText("EMAIL");
        eCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCheckActionPerformed(evt);
            }
        });
        enablerPanel.add(eCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, 20));

        profilePanel.add(enablerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, 70));

        jLabel12.setText("TEAM ");
        profilePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        bgPanel.add(profilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, 410));

        topBarPanel.setBackground(new java.awt.Color(0, 102, 102));
        topBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topBarPanelMouseDragged(evt);
            }
        });
        topBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topBarPanelMousePressed(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/x-button.png"))); // NOI18N
        exit.setText(" ");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        minimize.setText(" ");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ACQUAINTANCE PARTY");

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarPanelLayout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(321, 321, 321)
                .addComponent(minimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit)
                .addGap(6, 6, 6))
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(minimize)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        bgPanel.add(topBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 50));

        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORT");
        buttonPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DELETE");
        buttonPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 40, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SAVE");
        buttonPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 40, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADD");
        buttonPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 40, -1));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        delete.setToolTipText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        buttonPanel.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 40, 40));

        addProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addProfile.setToolTipText("ADD");
        addProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfileActionPerformed(evt);
            }
        });
        buttonPanel.add(addProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 40));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/download.png"))); // NOI18N
        save.setToolTipText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        buttonPanel.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 40));

        searchStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info.png"))); // NOI18N
        searchStudent.setToolTipText("SEARCH");
        searchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentActionPerformed(evt);
            }
        });
        buttonPanel.add(searchStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 40, 40));

        editStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/resume.png"))); // NOI18N
        editStudent.setToolTipText("EDIT");
        editStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentActionPerformed(evt);
            }
        });
        buttonPanel.add(editStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 40, 40));

        openFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/locked.png"))); // NOI18N
        openFile.setToolTipText("OPEN FILE");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        buttonPanel.add(openFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 40, 40));

        reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bar-chart.png"))); // NOI18N
        reports.setToolTipText("GENERATE REPORT");
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });
        buttonPanel.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 40, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SEARCH");
        buttonPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("FILE");
        buttonPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 40, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SORT");
        buttonPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 40, -1));

        sort.setForeground(new java.awt.Color(204, 204, 204));
        sort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sort (1).png"))); // NOI18N
        sort.setToolTipText("SORT");
        sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortActionPerformed(evt);
            }
        });
        buttonPanel.add(sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 40, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("EDIT");
        buttonPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 40, -1));

        timeIn.setText("TIME IN");
        timeIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeInMouseClicked(evt);
            }
        });
        timeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeInActionPerformed(evt);
            }
        });
        buttonPanel.add(timeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 80, 20));

        sortName.setText("FULL NAME");
        sortName.setToolTipText("");
        sortName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortNameMouseClicked(evt);
            }
        });
        sortName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortNameActionPerformed(evt);
            }
        });
        buttonPanel.add(sortName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SORT DATA BY");
        buttonPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        sortSno.setText("SNO");
        sortSno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortSnoMouseClicked(evt);
            }
        });
        sortSno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortSnoActionPerformed(evt);
            }
        });
        buttonPanel.add(sortSno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 80, 20));

        bgPanel.add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 110, 410));

        logoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setText("LOGO");
        logoPanel.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 60, 50));

        logo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo8.setText("LOGO");
        logoPanel.add(logo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 50));

        logo9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo9.setText("LOGO");
        logoPanel.add(logo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 50));

        logo10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo10.setText("LOGO");
        logoPanel.add(logo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 60, 50));

        logo11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo11.setText("LOGO");
        logoPanel.add(logo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 60, 50));

        logo12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo12.setText("LOGO");
        logoPanel.add(logo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 60, 50));

        logo13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo13.setText("LOGO");
        logoPanel.add(logo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 60, 50));

        bgPanel.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 230, 170));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printSno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printSno.setText("STUDENT NUMBER");
        jPanel1.add(printSno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 20));

        printFname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printFname.setText("FIRSTNAME");
        jPanel1.add(printFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 20));

        printLname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printLname.setText("LASTNAME");
        jPanel1.add(printLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 20));

        printGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printGender.setText("GENDER");
        jPanel1.add(printGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 20));

        printCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printCourse.setText("COURSE/");
        jPanel1.add(printCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 20));

        printYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printYear.setText("YEAR");
        jPanel1.add(printYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 40, 20));

        printCnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printCnumber.setText("09204272142");
        jPanel1.add(printCnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 20));

        printEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printEmail.setText("dkonogets@yahoo.com");
        jPanel1.add(printEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 210, 20));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TEAM LOGO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 70, 20));

        imageLabel.setBackground(new java.awt.Color(153, 153, 153));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imageX.png"))); // NOI18N
        imageLabel.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 100, 100));

        printTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printTime.setText("TIME IN");
        jPanel1.add(printTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 20));

        printTime1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printTime1.setText("I SOLO CODE");
        jPanel1.add(printTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 100, 20));

        bgPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 230, 230));

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentActionPerformed
        // TODO add your handling code here:
        try {
            ds.setStudentNo(snField.getText());
            searchStudent(ds.getStudentNo());

            getFields();
            fillPage();
//            jTable1.getSelectionModel().setSelectionInterval(ds.getRowSearch(),ds.getRowSearch());
//            if () {
//                
//            }
            clearTable();
            showTable();

        } catch (Exception e) {
            System.out.println("ESDAD");
            JOptionPane.showMessageDialog(null, "NO SUCH STUDENT");

        }


    }//GEN-LAST:event_searchStudentActionPerformed

    private void nameCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCheckActionPerformed

        enabler();

    }//GEN-LAST:event_nameCheckActionPerformed

    private void cyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyCheckActionPerformed

        enabler();

    }//GEN-LAST:event_cyCheckActionPerformed

    private void gCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gCheckActionPerformed
        enabler();
    }//GEN-LAST:event_gCheckActionPerformed

    private void cnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnCheckActionPerformed
        enabler();
    }//GEN-LAST:event_cnCheckActionPerformed

    private void eCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCheckActionPerformed
        enabler();
    }//GEN-LAST:event_eCheckActionPerformed

    private void yearBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearBoxActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null,
                "Do you want to proceed?", "DELETE!", JOptionPane.YES_NO_OPTION);
        if (input == 0) {
            try {
                ds.setStudentNo(snField.getText());
                ds.delUser();
            } catch (Exception e) {

                System.out.println(e);

            }
        }
        clearTable();
        showTable();
    }//GEN-LAST:event_deleteActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void topBarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarPanelMousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_topBarPanelMousePressed

    private void topBarPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarPanelMouseDragged
        // TODO add your handling code here:
        int positionX = evt.getXOnScreen();
        int positionY = evt.getYOnScreen();

        this.setLocation(positionX - mousePX, positionY - mousePY);
    }//GEN-LAST:event_topBarPanelMouseDragged

    private void fnFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnFieldMouseClicked
        if (fnField.getText().equals("FIRST NAME") && nameCheck.isSelected()) {
            fnField.setText("");
        }
    }//GEN-LAST:event_fnFieldMouseClicked

    private void lnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnFieldActionPerformed

    private void contactFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactFieldMouseClicked
        // TODO add your handling code here:
        if (contactField.getText().equals("CONTACT NO.") && cnCheck.isSelected()) {
            contactField.setText("");
        }
    }//GEN-LAST:event_contactFieldMouseClicked

    private void emailFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailFieldMouseClicked
        // TODO add your handling code here:
        if (emailField.getText().equals("E-MAIL") && eCheck.isSelected()) {
            emailField.setText("");
        }
    }//GEN-LAST:event_emailFieldMouseClicked

    private void addProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfileActionPerformed
        try {
            setFields();
            ds.addUser();
            clearTable();
            showTable();

        } catch (Exception e) {
        }

    }//GEN-LAST:event_addProfileActionPerformed

    private void snFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snFieldActionPerformed

    private void snFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snFieldMouseClicked
        // TODO add your handling code here:
        if (snField.getText().equals("STUDENT NUMBER")) {
            snField.setText("");
        }
    }//GEN-LAST:event_snFieldMouseClicked
    int counter = 1;
    private void editStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentActionPerformed
        counter++;
        if (counter % 2 == 0) {
            nameCheck.setSelected(true);
            cyCheck.setSelected(true);
            gCheck.setSelected(true);
            cnCheck.setSelected(true);
            eCheck.setSelected(true);
            enabler();
        } else {
            nameCheck.setSelected(false);
            cyCheck.setSelected(false);
            gCheck.setSelected(false);
            cnCheck.setSelected(false);
            eCheck.setSelected(false);
            enabler();
        }


    }//GEN-LAST:event_editStudentActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        int input = JOptionPane.showConfirmDialog(null,
                "Do you want to proceed?", "SAVE EDIT!", JOptionPane.YES_NO_OPTION);
        if (input == 0) {
            try {
                setFields();
                ds.updateUser();
            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, "WRONG INPUTS");
                System.out.println(e);

            }

        } else {
        }
        clearTable();
        showTable();


    }//GEN-LAST:event_saveActionPerformed

    private void fnFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnFieldMouseExited
        // TODO add your handling code here:


    }//GEN-LAST:event_fnFieldMouseExited

    private void lnFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnFieldMouseClicked
        if (lnField.getText().equals("LAST NAME") && nameCheck.isSelected()) {
            lnField.setText("");
        }
    }//GEN-LAST:event_lnFieldMouseClicked

    private void fnFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnFieldFocusLost
        if (fnField.getText().equals("")) {
            fnField.setText("FIRST NAME");
        }
    }//GEN-LAST:event_fnFieldFocusLost

    private void lnFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnFieldFocusLost
        if (lnField.getText().equals("")) {
            lnField.setText("LAST NAME");
        }
    }//GEN-LAST:event_lnFieldFocusLost

    private void contactFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFieldFocusLost
        if (contactField.getText().equals("")) {
            contactField.setText("CONTACT NO.");
        }
    }//GEN-LAST:event_contactFieldFocusLost

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        if (emailField.getText().equals("")) {
            emailField.setText("E-MAIL");
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void snFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_snFieldFocusLost
        // TODO add your handling code here:
        if (snField.getText().equals("")) {
            snField.setText("STUDENT NUMBER");
        }
    }//GEN-LAST:event_snFieldFocusLost

    private void courseBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseBoxActionPerformed

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        // TODO add your handling code here:

        try {
            Connection con = null;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ap_profiles", "root", "");
            JasperDesign jDesign = JRXmlLoader.load("C:\\Users\\jesss\\Documents\\NetBeansProjects\\codeRaceV3.0\\src\\records.jrxml");
            JRDesignQuery updateQuery = new JRDesignQuery();
            String query = ds.getSortQuery();

            updateQuery.setText(query);

            jDesign.setQuery(updateQuery);

            JasperReport jreport = JasperCompileManager.compileReport(jDesign);
            System.out.println("1");
            JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
            System.out.println("2");

            JasperViewer.viewReport(jprint, false, null);
            System.out.println("3");

        } catch (ClassNotFoundException | SQLException | JRException e) {
        }
    }//GEN-LAST:event_reportsActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        // TODO add your handling code here:
        printUser();

        try {
            Connection con = null;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ap_profiles", "root", "");
            JasperDesign jDesign = JRXmlLoader.load("C:\\Users\\jesss\\Documents\\NetBeansProjects\\codeRaceV3.0\\src\\report1.jrxml");
            JRDesignQuery updateQuery = new JRDesignQuery();
            String query = "SELECT * FROM `profiler` WHERE `s_number` =" + snField.getText();

            updateQuery.setText(query);

            jDesign.setQuery(updateQuery);

            JasperReport jreport = JasperCompileManager.compileReport(jDesign);
            System.out.println("1");
            JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
            System.out.println("2");

            JasperViewer.viewReport(jprint, false, null);
            System.out.println("3");

        } catch (ClassNotFoundException | SQLException | JRException e) {
        }
    }//GEN-LAST:event_openFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();

            imgLocation.setText(filename.substring(filename.lastIndexOf("\\") + 1, filename.length()));

            Image getAbsolutePath = null;
            ImageIcon icon = new ImageIcon(filename);

//        Image image = icon.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH)));

        } catch (NullPointerException e) {

            System.out.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnFieldActionPerformed

    private void snFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snFieldKeyTyped

        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }

    }//GEN-LAST:event_snFieldKeyTyped

    private void contactFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_contactFieldKeyTyped
    private void sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortActionPerformed
        clearTable();
        counter++;
        if (sortName.isSelected()) {
            if (counter % 2 == 0) {
                ds.setSortQuery("SELECT * FROM `profiler` ORDER BY `profiler`.`first_name` ASC");
                showTable();
            } else {
                ds.setSortQuery("SELECT * FROM `profiler` ORDER BY `profiler`.`first_name` DESC");
                showTable();
            }
        }

        if (sortSno.isSelected()) {
            if (counter % 2 == 0) {
                ds.setSortQuery("SELECT * FROM `profiler` ORDER BY `profiler`.`s_number` ASC");
                showTable();
            } else {
                ds.setSortQuery("SELECT * FROM `profiler` ORDER BY `profiler`.`s_number` DESC");
                showTable();
            }
        }
        if (timeIn.isSelected()) {
            if (counter % 2 == 0) {
                ds.setSortQuery("SELECT * FROM `profiler` ORDER BY `profiler`.`timeStamp` ASC");
                showTable();
            } else {
                ds.setSortQuery("SELECT * FROM `profiler` ORDER BY `profiler`.`timeStamp` DESC");
                showTable();
            }
        }

    }//GEN-LAST:event_sortActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int column = 0;
        int row = jTable1.getSelectedRow();
        String value = jTable1.getModel().getValueAt(row, column).toString();
        snField.setText(value.trim());
        System.out.println(String.valueOf(jTable1.getValueAt(row, column)));

        ds.setStudentNo(snField.getText());
        searchStudent(ds.getStudentNo());
        getFields();
        fillPage();

    }//GEN-LAST:event_jTable1MouseClicked

    private void sortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortNameActionPerformed

    private void timeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeInActionPerformed

    private void sortSnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortSnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortSnoActionPerformed

    private void sortNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortNameMouseClicked
        // TODO add your handling code here:
//        sortName.setSelected(false);
        sortSno.setSelected(false);
        timeIn.setSelected(false);
    }//GEN-LAST:event_sortNameMouseClicked

    private void sortSnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortSnoMouseClicked
        // TODO add your handling code here:
        sortName.setSelected(false);
//        sortSno.setSelected(false);
        timeIn.setSelected(false);
    }//GEN-LAST:event_sortSnoMouseClicked

    private void timeInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeInMouseClicked
        // TODO add your handling code here:
        sortName.setSelected(false);
        sortSno.setSelected(false);
//        timeIn.setSelected(false);
    }//GEN-LAST:event_timeInMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APAP().setVisible(true);
            }
        });
    }
    int mousePX, mousePY;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProfile;
    private javax.swing.JPanel bgPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JCheckBox cnCheck;
    private javax.swing.JTextField contactField;
    private javax.swing.JComboBox<String> courseBox;
    private javax.swing.JCheckBox cyCheck;
    private javax.swing.JButton delete;
    private javax.swing.JPanel dispayPanel;
    private javax.swing.JCheckBox eCheck;
    private javax.swing.JButton editStudent;
    private javax.swing.JTextField emailField;
    private javax.swing.JPanel enablerPanel;
    private javax.swing.JLabel enalblerTxt;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField fnField;
    private javax.swing.JCheckBox gCheck;
    private javax.swing.JComboBox<String> genderBox;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField imgLocation;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lnField;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo10;
    private javax.swing.JLabel logo11;
    private javax.swing.JLabel logo12;
    private javax.swing.JLabel logo13;
    private javax.swing.JLabel logo8;
    private javax.swing.JLabel logo9;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel minimize;
    private javax.swing.JCheckBox nameCheck;
    private javax.swing.JButton openFile;
    private javax.swing.JLabel printCnumber;
    private javax.swing.JLabel printCourse;
    private javax.swing.JLabel printEmail;
    private javax.swing.JLabel printFname;
    private javax.swing.JLabel printGender;
    private javax.swing.JLabel printLname;
    private javax.swing.JLabel printSno;
    private javax.swing.JLabel printTime;
    private javax.swing.JLabel printTime1;
    private javax.swing.JLabel printYear;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton reports;
    private javax.swing.JButton save;
    private javax.swing.JButton searchStudent;
    private javax.swing.JTextField snField;
    private javax.swing.JButton sort;
    private javax.swing.JCheckBox sortName;
    private javax.swing.JCheckBox sortSno;
    private javax.swing.JCheckBox timeIn;
    private javax.swing.JPanel topBarPanel;
    private javax.swing.JComboBox<String> yearBox;
    // End of variables declaration//GEN-END:variables
    doStuff ds = new doStuff();

    private void setFields() {
        ds.setfName(fnField.getText());
        ds.setlName(lnField.getText());
        ds.setCourse(courseBox.getSelectedItem().toString());
        ds.setContactNo(contactField.getText());
        ds.setYear(yearBox.getSelectedItem().toString());
        ds.seteMail(emailField.getText());
        ds.setGender(genderBox.getSelectedItem().toString());
        ds.setStudentNo(snField.getText());
        ds.setIMG(imgLocation.getText());

        ds.printProfile();
    }

    private void enabler() {
        if (cyCheck.isSelected()) {
            courseBox.setEnabled(true);
            yearBox.setEnabled(true);

        } else {
            courseBox.setEnabled(false);
            yearBox.setEnabled(false);
        }

        if (gCheck.isSelected()) {
            genderBox.setEnabled(true);
        } else {
            genderBox.setEnabled(false);
        }

        if (cnCheck.isSelected()) {
            contactField.setEnabled(true);
        } else {
            contactField.setEnabled(false);
            if (!contactField.getText().equals("CONTACT NO.")) {

            } else {
                contactField.setText("CONTACT NO.");
                System.out.println("conta?");
            }
        }

        if (eCheck.isSelected()) {
            emailField.setEnabled(true);
        } else {
            emailField.setEnabled(false);
            if (!emailField.getText().equals("E-MAIL")) {
                System.out.println("email?");
            } else {
                emailField.setText("E-MAIL");
            }
        }
        if (nameCheck.isSelected()) {
            fnField.setEnabled(true);
            lnField.setEnabled(true);
        } else {
            fnField.setEnabled(false);
            lnField.setEnabled(false);
            if (!fnField.getText().equals("FIRST NAME") && !lnField.getText().equals("LAST NAME")) {

            } else {
                lnField.setText("LAST NAME");
                fnField.setText("FIRST NAME");
            }
        }
    }

    private void searchStudent(String studentNo) {

        ds.sStudenetNum();
    }

    private void getFields() {

        fnField.setText(ds.getfName());
        lnField.setText(ds.getlName());
        contactField.setText(ds.getContactNo());
        emailField.setText(ds.geteMail());
        System.out.println(ds.getGender());

        switchItUp();
    }

    private void switchItUp() {
        switch (ds.getCourse()) {
            case "ACT":
                courseBox.setSelectedIndex(1);
                break;
            case "BSIT":
                courseBox.setSelectedIndex(2);
                break;
            case "BSCS":
                courseBox.setSelectedIndex(3);
                break;
            case "BSEMC":
                courseBox.setSelectedIndex(4);
                break;
            default:
        }
        switch (ds.getYear()) {
            case "1":
                yearBox.setSelectedIndex(1);
                break;
            case "2":
                yearBox.setSelectedIndex(2);
                break;
            case "3":
                yearBox.setSelectedIndex(3);
                break;
            case "4":
                yearBox.setSelectedIndex(4);
                break;
            default:
        }
        switch (ds.getGender()) {
            case "MALE":
                genderBox.setSelectedIndex(1);
                break;
            case "FEMALE":
                genderBox.setSelectedIndex(2);
                break;
            default:
                System.err.println("SHITS");
        }
    }
    static int rowSearch;

    public void showTable() {
        ds.userList().clear();
        ArrayList<User> list = ds.userList();

        jTable1.removeAll();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[3];

        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getStudentNum();
            row[1] = list.get(i).getFirstName() + " " + list.get(i).getLastName();
            row[2] = list.get(i).getDtr();

            model.fireTableStructureChanged();
            model.fireTableDataChanged();
            model.addRow(row);

        }
        System.out.println(model.getRowCount());
        list.clear();
    }

    private void printUser() {

    }

    private void fillPage() {

        try {
            printSno.setText(ds.getStudentNo());
            printFname.setText(ds.getfName());
            printLname.setText(ds.getlName());
            printGender.setText(ds.getGender());
            printCourse.setText(ds.getCourse());
            printYear.setText(ds.getYear());
            printCnumber.setText(ds.getContactNo());
            printEmail.setText(ds.geteMail());
            printTime.setText(ds.getTimeIn());
            imgLocation.setText(ds.getIMG());

            Image getAbsolutePath = null;
            String path = "C:\\Users\\jesss\\Desktop\\apapPic\\" + ds.getIMG();
            if (ds.getIMG().contains(" ")) {
                imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imageX.png")));
            } else {
                ImageIcon icon = new ImageIcon(ds.getIMG());
                imageLabel.setIcon(new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH)));
            }

        } catch (Exception e) {
            System.out.println("null image");
        }

    }

    private void updateTable() {
        int column = 0;
        int row = jTable1.getSelectedRow();
        String value = jTable1.getModel().getValueAt(row, column).toString();
        snField.setText(value.trim());

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setValueAt(fnField.getText() + " " + lnField.getText(), 0, 1);
    }

    private void sortTable() {

    }

    private void clearTable() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int tableCount = jTable1.getRowCount();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

    }

}
